### ISSUE TITLE
LiteSpeed SAPI Support

### ISSUE THREAD

**Issue by NCRonB** [lamskoy/arch-phpbs#1]
I use [OpenLiteSpeed](https://openlitespeed.org/) on Arch Linux with PHP versions 5.3, 5.6, 7.4, and 8 using my own PKGBUILD patches to build the lsphp binary with LiteSpeed SAPI support available in PHP>=5.3. I'd love to see it integrated into arch-phpbs. The attached diff works for me, but perhaps it could use some cleaning.

[arch-phpbs-litespeed.patch.zip](https://github.com/lamskoy/arch-phpbs/files/8077949/arch-phpbs-litespeed.patch.zip)

**Comment by lamskoy** [comment]
I'm ok to merge this. Can you make pull-request to my repo?

**Comment by lamskoy** [comment]
Thanks for contriubtion
