### ISSUE TITLE
AUR packages newer than arch-phpbs?

### ISSUE THREAD

**Issue by NCRonB** [lamskoy/arch-phpbs#4]
I've been using arch-phpbs to build PHP, but it hasn't been updated on GitHub as new PHP versions are released. However, I see that the AUR packages apparently based on arch-phpbs are the latest PHP versions. Will arch-phpbs be updated so I can use it to build my own packages of the latest PHP versions?

**Comment by lamskoy** [comment]
A bit delayed due to war in Ukraine. Merged PR with update, welcome to use

**Comment by NCRonB** [comment]
Yikes! Thank you, and stay safe!
