### ISSUE TITLE
No support for Berkeley DB 6

### ISSUE THREAD

**Issue by micwoj92** [lamskoy/arch-phpbs#7]
I've tried to build php73 package, it fails (it probably affects all version of php packaged by this script https://aur.archlinux.org/packages?K=php%20-dba)
```
checking for DB4 major version... configure: error: Header contains different version
```

Looking at configure 

```
--with-db4=DIR          DBA: Oracle Berkeley DB 4.x or 5.x support
```
It does not support db version 6. I've also checked configure of 8.2.0 and it's same.
I've checked php's bugtracker on GitHub and coudln't find any support requests for berkeley db 6 support. I suppose this is due to the controversial license change, do you think it is worth opening issue about that upstream?

**Comment by micwoj92** [comment]
Oh, I've just checked and it was already reported on php80 by @henschi I guess I will leave this open since it affects all packages.

**Comment by pavel-monro** [comment]
Yes, there is a problem, it is not possible to install the package for this reason

**Comment by nikspyratos** [comment]
Link to the comment referenced: https://aur.archlinux.org/packages/php80#comment-894857

**Comment by micwoj92** [comment]
Fyi official php package had patch for db6, but it was removed.
https://github.com/archlinux/svntogit-packages/commit/dfa693ce4bad61190a64b7c423651653973613ce
https://github.com/archlinux/svntogit-packages/commit/7d55fa3397be470457e63a556dbac4359f90d26b
https://github.com/archlinux/svntogit-packages/commit/0136743bad94f2ce81d27000e38441c2de4e861f

**Comment by lamskoy** [comment]
Have made fix already ;)

**Comment by lamskoy** [comment]
uses 5.3 berkley DB, not 6.x for now
