### ISSUE TITLE
Add imagick extension ?

### ISSUE THREAD

**Issue by Striffly** [lamskoy/arch-phpbs#9]
Hello,
Would it be possible to add the imagick extension build for each version of PHP?

Also, thank you very much for this awesome work.

**Comment by lamskoy** [comment]
Imagick is PECL 3rd party extension, not a part of PHP core.
phpbs builds only basic PHP distribution and won't be shipped with any 3rd party extensions ever

Option one - install AUR package phpXX-imagick for needed version

Option two:

You can easilly build with pecl command by yourself. 
There's subpackage phpXX-pecl which is generated by phpbs
Assuming you have installed php83 group of packages:


```
pacman -Q | grep pecl
sudo pecl83 channel-update pecl.php.net
sudo pecl83 install imagick
extension=imagick.so | sudo tee /etc/php83/conf.d/30-imagick.ini
php83 - m | grep imagick
```
now you have it installed if php83 -m shows "imagick" in output

**Comment by Striffly** [comment]
Noted, thank you!
